### ISSUE TITLE
Documented way to use custom form controls broken in 4.0.0-rc.2 & later

### ISSUE THREAD

**Issue by kitsuneyo** [kaliber5/ember-bootstrap#1192]
The documented way to use custom form controls, such as [Ember Pikaday](https://github.com/adopted-ember-addons/ember-pikaday), is broken in releases `4.0.0-rc.2` and later. It raises the error `Assertion Failed: You cannot set both property and value on a form element` when the control value is changed.

Maybe this is related to PR #1097 "Remove leftover two-way binding of form element's `@value` argument".

Here is the [example from the documentation](https://www.ember-bootstrap.com/api/classes/Components.FormElement.html):

```
<BsForm @model={{this}} @onSubmit={{action "submit"}} as |form|>
  <form.element @label="Select-2" @property="gender" @useIcons={{false}} as |el|>
    <PikadayInput @value={{el.value}} @onSelection={{action (mut el.value)}} id={{el.id}} />
  </form.element>
</BsForm>
```

Here is my implementation:

```
<form.element
  @label={{t "forms.profile.birthday.label"}}
  @property="birthday"
  as |el|
>
  <PikadayInput
    @value={{el.value}}
    @class={{el.validation}}
    @onSelection={{action (mut el.value)}}
    id={{el.id}}
  />
</form.element>
```

Here are the package versions I'm using. I've also tried `4.0.0`. Everything prior to `rc.2` works.

```
DEBUG: -------------------------------
DEBUG: Ember             : 3.18.1
DEBUG: Ember Data        : 3.18.0
DEBUG: Ember Bootstrap   : 4.0.0-rc.2
DEBUG: Ember Simple Auth : 3.1.0-beta.0
DEBUG: -------------------------------
```

Full error output (in testing):

```
Source: | Error: Assertion Failed: You cannot set both property and value on a form element
     at Object.assert (http://localhost:4202/assets/vendor.js:41817:15)
     at BsFormElementWithChangesetValidationsSupport.set value [as value (http://localhost:4202/assets/vendor.js:102326:57)
     at setWithMandatorySetter (http://localhost:4202/assets/vendor.js:37040:22)
     at set (http://localhost:4202/assets/vendor.js:20653:43)
     at PropertyReference.[UPDATE_REFERENCED_VALUE] (http://localhost:4202/assets/vendor.js:52967:16)
     at MutReference.__INVOKE__ember15980008601611513244063377__ (http://localhost:4202/assets/vendor.js:11850:60)
     at Backburner._join (http://localhost:4202/assets/vendor.js:63208:23)
     at Backburner.join (http://localhost:4202/assets/vendor.js:62973:19)
     at join (http://localhost:4202/assets/vendor.js:46805:23)
     at http://localhost:4202/assets/vendor.js:12260:34
```

**Comment by jelhan** [comment]
I was able to reproduce this bug with an even simpler setup:

```hbs
<BsForm @model={{hash name=""}} as |form|>
  <form.element @property="name" as |el|>
    <input type="text" value={{el.value}} {{on "change" (action (mut el.value) target="target.value")}} />
  </form.element>
</BsForm>
```

Seems as if mutating yielded `{{el.value}}` throws. I think this is a common pattern, which we should support. Wondering that our test suite doesn't cover this.
