### ISSUE TITLE
Cannot read property 'ember-bootstrap' of undefined

### ISSUE THREAD

**Issue by GCorbel** [kaliber5/ember-bootstrap#120]
In and Ember 2.7 app, [at this line](https://github.com/kaliber5/ember-bootstrap/blob/master/index.js#L26) I have this error : 

    Cannot read property 'ember-bootstrap' of undefined

If I do `app = app.app` it workes. I'm not working on an addon and the if statement is not true.

I don't know what's the definitive solution. What you think?

**Comment by simonihmig** [comment]
I have no idea, but ember-bootstrap has a lot of tests that also run for ember 2.7, so really there should be no problem in general. I think there must be something with your particular app. I just recently set up a fresh app with ember-cli 2.7 / ember 2.7 without any problems, so the problem must lie somewhere else unfortunately!

**Comment by GCorbel** [comment]
@simonihmig I tried to contribute to [this addon](https://github.com/quantosobra/ember-data-table-light) and I have the problem. I don't see anything special. Please, can you check it?

**Comment by GCorbel** [comment]
Sorry, I was wrong. Your addon seems to be correct. Thanks.

**Comment by GCorbel** [comment]
I finally found a way to reproduce the bug. I when `ember-bootstrap` is an dependency of an addon. For example, a package with this in `package.json` : 

```
{
  ...
  "dependencies": {
    "ember-cli-babel": "^5.1.3",
    "ember-bootstrap": "0.10.0"
  }
  ...
}
```

And I have this stack trace : 

```
Cannot read property 'ember-bootstrap' of undefined
TypeError: Cannot read property 'ember-bootstrap' of undefined
    at CoreObject.included (/frontend/node_modules/ember-bootstrap/index.js:26:53)
    at /frontend/node_modules/ember-cli/lib/models/addon.js:258:34
    at Array.map (native)
    at CoreObject.eachAddonInvoke (/frontend/node_modules/ember-cli/lib/models/addon.js:252:24)
    at CoreObject.extend.included (/frontend/node_modules/ember-cli/lib/models/addon.js:435:10)
    at CoreObject.superWrapper [as included] (/frontend/node_modules/core-object/lib/assign-properties.js:32:18)
    at EmberApp.<anonymous> (/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:468:15)
    at Array.filter (native)
    at EmberApp._notifyAddonIncluded (/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:463:45)
    at new EmberApp (/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:136:8)
    at module.exports (/frontend/ember-cli-build.js:7:15)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/frontend/node_modules/ember-cli/lib/models/builder.js:74:19)
    at CoreObject.module.exports.Task.extend.init (/frontend/node_modules/ember-cli/lib/models/builder.js:54:10)
    at CoreObject.superWrapper [as init] (/frontend/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/frontend/node_modules/core-object/core-object.js:32:33)
    at CoreObject.module.exports.Task.extend.run (/frontend/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at CoreObject.<anonymous> (/frontend/node_modules/ember-cli/lib/commands/test.js:164:27)
    at tryCatch (/frontend/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/frontend/node_modules/rsvp/dist/rsvp.js:553:13)
    at /frontend/node_modules/rsvp/dist/rsvp.js:628:16
    at flush (/frontend/node_modules/rsvp/dist/rsvp.js:2370:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

I don't understand why it do that... can you help me?

**Comment by viniciussbs** [comment]
@GCorbel Same here: I have an addon that includes `ember-bootstrap` as its dependency. When I install the addon into another app, I have this error.

**Comment by srvance** [comment]
@viniciussbs @GCorbel Can you share the addons that include `ember-bootstrap` with us?

Can you tell us what versions of ember, ember-cli, and ember-bootstrap you're using?

**Comment by viniciussbs** [comment]
@srvance It's my own private addon with core UI componentes shared with other apps.

```
$ ember -v
ember-cli: 2.11.0
```
`"ember-bootstrap": "0.11.1"`

One of the apps already have `ember-bootstrap` (same version) into `"devDependencies"` as its own dependency.

**Comment by Charizard** [comment]
Same here. My case exactly is similar to @viniciussbs

**Comment by srvance** [comment]
Any chance you can upgrade to the latest? We're not making changes to the `0.*` versions, and there have been several changes to how the hosting app is identified.

We know that there are some issues with ember-bootstrap as an addon dependency, at least one of which is that ember-cli doesn't have a story for running blueprints of addon dependencies.

**Comment by Charizard** [comment]
@srvance I did point to master and it worked like charm. Thanks 🌮
