### ISSUE TITLE
Embroider build error in ember-bootstrap 4.9.0 using bootstrap 3

### ISSUE THREAD

**Issue by bryanhickerson** [kaliber5/ember-bootstrap#1726]
Thank you for taking the time to open an issue!

For general questions please use the #e-bootstrap channel on the [Ember Discord server](https://discord.gg/zT3asNS).

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

---

Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^4.9.0 -> 4.9.0
ember-cli: ~3.28.5 -> 3.28.5
bootstrap: n/a
bootstrap-sass: n/a
ember-cli-sass: ^10.0.1 -> 10.0.1
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 3
importBootstrapFont: false
importBootstrapCSS: false
whitelist: undefined
```

```
@embroider/macros Error (Analyzer)

/Users/bryan/dev/betterup-app/frontend/ember-bootstrap/components/bs-popover/element.js: the first argument to macroCondition must be statically known
  19 |    */
  20 |
> 21 |   arrowClass = macroCondition(getOwnConfig().isBS5) ? 'popover-arrow' : 'arrow';
     |                               ^^^^^^^^^^^^^^^^^^^^
  22 |   placementClassPrefix = 'bs-popover-';
  23 |   offset = [0, macroCondition(getOwnConfig().isBS5) ? 8 : 0];
  24 | }


Stack Trace and Error Report: /var/folders/wq/g60z4g5x58zg488cjsf70z6w0000gp/T/error.dump.4628ff9950b2991dfd1c1087ab934371.log
```

**Comment by simonihmig** [comment]
Are you actually using Embroider (as the title suggests), or is this a "classic" Ember CLI build?

I am not sure what is happening here. A possible cause could be some variant of dependency hell... could you check if you have multiple copies of the `@embroider/macros` package? Using `yarn`, this would be e.g. `yarn why @embroider/macros`.

Again, when using `yarn`, running `npx yarn-deduplicate` sometimes works wonders.

**Comment by bryanhickerson** [comment]
>Are you actually using Embroider (as the title suggests), or is this a "classic" Ember CLI build?

I am not, this is a classic build. I'll try deduping.

**Comment by bryanhickerson** [comment]
Looks like it's being included many times.

```
yarn why @embroider/macros
yarn why v1.22.17
[1/4] 🤔  Why do we have the module "@embroider/macros"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@embroider/macros@0.41.0"
info Has been hoisted to "@embroider/macros"
info Reasons this module exists
   - Hoisted from "@embroider#util#@embroider#macros"
   - Hoisted from "ember-bootstrap#@embroider#macros"
   - Hoisted from "ember-bootstrap#ember-focus-trap#@embroider#macros"
info Disk size without dependencies: "1.71MB"
info Disk size with unique dependencies: "12.08MB"
info Disk size with transitive dependencies: "141.18MB"
info Number of shared dependencies: 240
=> Found "ember-classic-decorator#@embroider/macros@0.29.0"
info This module exists because "ember-classic-decorator" depends on it.
info Disk size without dependencies: "364KB"
info Disk size with unique dependencies: "40.14MB"
info Disk size with transitive dependencies: "207.43MB"
info Number of shared dependencies: 302
=> Found "ember-exam#@embroider/macros@0.36.0"
info Reasons this module exists
   - "ember-exam" depends on it
   - Hoisted from "ember-exam#@embroider#macros#@embroider#core#@embroider#macros"
info Disk size without dependencies: "376KB"
info Disk size with unique dependencies: "40.15MB"
info Disk size with transitive dependencies: "207.44MB"
info Number of shared dependencies: 302
=> Found "@ember/render-modifiers#@embroider/macros@1.0.0"
info This module exists because "@ember#render-modifiers" depends on it.
info Disk size without dependencies: "460KB"
info Disk size with unique dependencies: "10.91MB"
info Disk size with transitive dependencies: "139.93MB"
info Number of shared dependencies: 240
=> Found "@sentry/ember#@embroider/macros@0.47.2"
info This module exists because "@sentry#ember" depends on it.
info Disk size without dependencies: "472KB"
info Disk size with unique dependencies: "10.88MB"
info Disk size with transitive dependencies: "139.94MB"
info Number of shared dependencies: 240
=> Found "ember-power-select#@embroider/macros@0.47.2"
info Reasons this module exists
   - "ember-power-select#@embroider#util" depends on it
   - Hoisted from "ember-power-select#@embroider#util#@embroider#macros"
info Disk size without dependencies: "472KB"
info Disk size with unique dependencies: "10.88MB"
info Disk size with transitive dependencies: "139.94MB"
info Number of shared dependencies: 240
=> Found "ember-cli-flash#@embroider/macros@0.50.0"
info Reasons this module exists
   - "ember-cli-flash#@ember#render-modifiers" depends on it
   - Hoisted from "ember-cli-flash#@ember#render-modifiers#@embroider#macros"
info Disk size without dependencies: "472KB"
info Disk size with unique dependencies: "10.88MB"
info Disk size with transitive dependencies: "139.94MB"
info Number of shared dependencies: 240
=> Found "ember-basic-dropdown#@embroider/macros@0.47.2"
info Reasons this module exists
   - "ember-power-select#ember-basic-dropdown" depends on it
   - Hoisted from "ember-power-select#ember-basic-dropdown#@embroider#util#@embroider#macros"
info Disk size without dependencies: "472KB"
info Disk size with unique dependencies: "10.88MB"
info Disk size with transitive dependencies: "139.94MB"
info Number of shared dependencies: 240
=> Found "@sentry/ember#ember-auto-import#@embroider/macros@1.0.0"
info This module exists because "@sentry#ember#ember-auto-import" depends on it.
info Disk size without dependencies: "460KB"
info Disk size with unique dependencies: "10.91MB"
info Disk size with transitive dependencies: "139.93MB"
info Number of shared dependencies: 240
=> Found "ember-in-viewport#@embroider/macros@1.0.0"
info Reasons this module exists
   - "ember-in-viewport#ember-auto-import" depends on it
   - Hoisted from "ember-in-viewport#ember-auto-import#@embroider#macros"
info Disk size without dependencies: "460KB"
info Disk size with unique dependencies: "10.91MB"
info Disk size with transitive dependencies: "139.93MB"
info Number of shared dependencies: 240
=> Found "@embroider/core#@embroider/macros@0.29.0"
info This module exists because "ember-classic-decorator#@embroider#macros#@embroider#core" depends on it.
info Disk size without dependencies: "364KB"
info Disk size with unique dependencies: "40.14MB"
info Disk size with transitive dependencies: "207.43MB"
info Number of shared dependencies: 302
=> Found "ember-exam#ember-auto-import#@embroider/macros@0.33.0"
info Reasons this module exists
   - "ember-exam#ember-auto-import#@embroider#core" depends on it
   - Hoisted from "ember-exam#ember-auto-import#@embroider#core#@embroider#macros"
info Disk size without dependencies: "376KB"
info Disk size with unique dependencies: "40.15MB"
info Disk size with transitive dependencies: "207.44MB"
info Number of shared dependencies: 302
=> Found "ember-bootstrap#@embroider/core#@embroider/macros@0.33.0"
info This module exists because "ember-bootstrap#ember-auto-import#@embroider#core" depends on it.
info Disk size without dependencies: "376KB"
info Disk size with unique dependencies: "40.15MB"
info Disk size with transitive dependencies: "207.44MB"
info Number of shared dependencies: 302
=> Found "ember-freestyle#@embroider/macros@0.33.0"
info Reasons this module exists
   - "ember-freestyle#ember-auto-import#@embroider#core" depends on it
   - Hoisted from "ember-freestyle#ember-auto-import#@embroider#core#@embroider#macros"
info Disk size without dependencies: "376KB"
info Disk size with unique dependencies: "40.15MB"
info Disk size with transitive dependencies: "207.44MB"
info Number of shared dependencies: 302
=> Found "ember-qunit#@embroider/macros@0.33.0"
info Reasons this module exists
   - "ember-qunit#ember-auto-import#@embroider#core" depends on it
   - Hoisted from "ember-qunit#ember-auto-import#@embroider#core#@embroider#macros"
info Disk size without dependencies: "376KB"
info Disk size with unique dependencies: "40.15MB"
info Disk size with transitive dependencies: "207.44MB"
info Number of shared dependencies: 302
=> Found "ember-data-factory-guy#@embroider/macros@0.33.0"
info Reasons this module exists
   - "ember-data-factory-guy#ember-auto-import#@embroider#core" depends on it
   - Hoisted from "ember-data-factory-guy#ember-auto-import#@embroider#core#@embroider#macros"
info Disk size without dependencies: "376KB"
info Disk size with unique dependencies: "40.15MB"
info Disk size with transitive dependencies: "207.44MB"
info Number of shared dependencies: 302
=> Found "ember-intl#@embroider/macros@0.33.0"
info Reasons this module exists
   - "ember-intl#ember-auto-import#@embroider#core" depends on it
   - Hoisted from "ember-intl#ember-auto-import#@embroider#core#@embroider#macros"
info Disk size without dependencies: "376KB"
info Disk size with unique dependencies: "40.15MB"
info Disk size with transitive dependencies: "207.44MB"
info Number of shared dependencies: 302
=> Found "ember-focus-trap#@embroider/core#@embroider/macros@0.33.0"
info This module exists because "ember-bootstrap#ember-focus-trap#ember-auto-import#@embroider#core" depends on it.
info Disk size without dependencies: "376KB"
info Disk size with unique dependencies: "40.15MB"
info Disk size with transitive dependencies: "207.44MB"
info Number of shared dependencies: 302
=> Found "ember-infinity#@embroider/macros@0.33.0"
info Reasons this module exists
   - "ember-infinity#ember-in-viewport#ember-auto-import#@embroider#core" depends on it
   - Hoisted from "ember-infinity#ember-in-viewport#ember-auto-import#@embroider#core#@embroider#macros"
info Disk size without dependencies: "376KB"
info Disk size with unique dependencies: "40.15MB"
info Disk size with transitive dependencies: "207.44MB"
info Number of shared dependencies: 302
✨  Done in 16.51s.
```

yarn-deduplicate seems blow up on `@embroider/macros`. I've used it before with no issue.
```
npx yarn-deduplicate "@embroider/macros"
npx: installed 6 in 0.934s
Error: ENOENT: no such file or directory, open '@embroider/macros'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at Object.<anonymous> (/Users/bryan/.npm/_npx/32542/lib/node_modules/yarn-deduplicate/cli.js:49:25)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at /usr/local/Cellar/node@14/14.18.1/lib/node_modules/npm/node_modules/libnpx/index.js:268:14 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '@embroider/macros'
}
```

**Comment by simonihmig** [comment]
This seems to be related to https://github.com/embroider-build/embroider/issues/1077. Please see especially Ed's [last comment](https://github.com/embroider-build/embroider/issues/1077#issuecomment-1016689755), hope this helps!?

**Comment by bryanhickerson** [comment]
Thanks I'll give it a shot!

**Comment by bryanhickerson** [comment]
Confirmed adding `"@embroider/macros": "^1.0.0",` to resolutions addressed the build failure.
