### ISSUE TITLE
Default blueprint fails for unexpected `ember-cli-build.js` structure

### ISSUE THREAD

**Issue by rstudner** [kaliber5/ember-bootstrap#279]
I get this:
```
07:48 $ ember generate ember-bootstrap
installing ember-bootstrap
Installing for Bootstrap 3 using preprocessor sass
  uninstall bower package bootstrap
  uninstall package bootstrap
  install package bootstrap-sass
NPM: Uninstalled bootstrap

NPM: Installed bootstrap-sass@^3.3.7
Added import statement to app/styles/app.scss
Added ember-bootstrap configuration to ember-cli-build.js
Cannot read property 'properties' of undefined
TypeError: Cannot read property 'properties' of undefined
    at EmberBuildConfigEditor.findOrAddConfigKey (/Users/rstudner/projects/expel-ember/node_modules/ember-cli-build-config-editor/lib/build-config-editor.js:52:36)
    at EmberBuildConfigEditor.edit (/Users/rstudner/projects/expel-ember/node_modules/ember-cli-build-config-editor/lib/build-config-editor.js:95:40)
    at Class.addBuildConfiguration (/Users/rstudner/projects/expel-ember/node_modules/ember-bootstrap/blueprints/ember-bootstrap/index.js:193:28)
    at adjustBootstrapDependencies.then.then.then (/Users/rstudner/projects/expel-ember/node_modules/ember-bootstrap/blueprints/ember-bootstrap/index.js:73:24)
    at tryCatch (/Users/rstudner/projects/expel-ember/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/rstudner/projects/expel-ember/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/rstudner/projects/expel-ember/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/rstudner/projects/expel-ember/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by rstudner** [comment]
Here is my ember-cli-build.js:
```
/* global require, module */
const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  let environment = EmberApp.env();

  let config = {
    'babelConfig': {},
    'ember-cli-qunit': {
      useLintTree: true
    },
    'ember-cli-babel': {
      includePolyfill: true
    },
    'ember-bootstrap': {
      'importBootstrapCSS': false,
    },
    'numeral': {
      includeLanguages: true
    },
    'sassOptions': {
      sourceMap: true,
    },
    'sourcemaps': {
      enabled: EmberApp.env() !== 'production',
      // enabled: true,
      extensions: ['js'],
    }
    // Add options here
  };
  if (environment === 'development') {
    config.babelConfig = {
      blacklist: [
        'es6.arrowFunctions',
        'es6.blockScoping',
        'es6.classes',
        'es6.constants',
        'es6.destructuring',
        'es6.forOf',
        'es6.parameters',
        'es6.properties.computed',
        'es6.properties.shorthand',
        'es6.spread',
        'es6.tailCall',
        'es6.templateLiterals',
        'es6.regex.unicode',
        'es6.regex.sticky',
        'regenerator'
      ]
    };
  }
  let app = new EmberApp(defaults, config);

  app.import('bower_components/mdi/css/materialdesignicons.min.css');
  app.import('bower_components/mdi/fonts//materialdesignicons-webfont.eot', { destDir: 'fonts' });
  app.import('bower_components/mdi/fonts//materialdesignicons-webfont.svg', { destDir: 'fonts' });
  app.import('bower_components/mdi/fonts//materialdesignicons-webfont.ttf', { destDir: 'fonts' });
  app.import('bower_components/mdi/fonts/materialdesignicons-webfont.woff', { destDir: 'fonts' });
  app.import('bower_components/mdi/fonts/materialdesignicons-webfont.woff2', { destDir: 'fonts' });
  return app.toTree();
};

```

**Comment by rwjblue** [comment]
I reported https://github.com/srvance/ember-cli-build-config-editor/issues/3, I believe that is the root of the issue here.

**Comment by srvance** [comment]
Ah. I'm making the naive assumption the configuration object is inline with the `new`.

**Comment by simonihmig** [comment]
@rstudner the problem is indeed the somewhat "unusual" (but still perfectly valid, no doubts!) structure of your `ember-cli-build.js`. We try to edit that file automatically to explicitly set the config, but in this case this fails.

We will have to fix that as is suggested in the other filed issue. For now you should be able to work around this by not using `ember g ember-bootstrap`. Instead you have to manually update your dependencies. I assume you use Bootstrap 3 and `ember-cli-sass`? Then do the following:
* add `bootstrap-sass@^3.3.7` to your npm dependencies (if required)
* remove any bootstrap dependency from your `bower.json`

Hopefully you should be able to upgrade your project nevertheless, while we will fix this issue...

**Comment by rstudner** [comment]
Wanted to commit before alpha9 comes out or someone points at master.  The above instructions (for Sass and 3.3.7) work 100%.  Just wanted to provide a thumbs up on them so if someone finds this they can be confident it unblocks them in the short term.

**Comment by simonihmig** [comment]
@rstudner Cool, thanks! Also @srvance just provided a fix for the issue. If you want to try that out, you can do so by using the latest `kaliber5/ember-bootstrap#master` in your `package.json`. With that the `ember g ember-bootstrap` command should issue a warning now, but not fail as before! 

Would be nice if you would be able to confirm!

**Comment by rstudner** [comment]
Verified warning appears as expected and that manually editing results in a working version.

**Comment by simonihmig** [comment]
Great! Thanks a lot for supporting us here! 👍
