### ISSUE TITLE
Ember 1.13.13: no such file or directory on brand new project

### ISSUE THREAD

**Issue by neilyoung** [kaliber5/ember-bootstrap#35]
ENOENT: no such file or directory, stat '/Users/me/Projects/bs/tmp/concat_with_maps-input_base_path-4RsHvtY9.tmp/0/bower_components/bootstrap/js/transition.js'
    Error: ENOENT: no such file or directory, stat '/Users/me/Projects/bs/tmp/concat_with_maps-input_base_path-4RsHvtY9.tmp/0/bower_components/bootstrap/js/transition.js'
        at Error (native)
        at Object.fs.statSync (fs.js:892:18)
        at ConcatWithMaps.keyForFile (/Users/me/Projects/bs/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:90:20)
        at Array.map (native)
        at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/me/Projects/bs/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:112:65)
        at /Users/me/Projects/bs/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
        at lib$rsvp$$internal$$tryCatch (/Users/me/Projects/bs/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
        at lib$rsvp$$internal$$invokeCallback (/Users/me/Projects/bs/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
        at lib$rsvp$$internal$$publish (/Users/me/Projects/bs/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
        at lib$rsvp$asap$$flush (/Users/me/Projects/bs/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    

right after npm install && bower install && ember server

**Comment by neilyoung** [comment]
bower install bootstrap

solved the problem. Wasn't aware of this requirement.

**Comment by simonihmig** [comment]
How did you install the addon? Using `ember install ember-bootstrap` should have added bootstrap to your bower.json and installed it automatically!

**Comment by neilyoung** [comment]
Installed it like you said: ember install ember-bootstrap

**Comment by simonihmig** [comment]
Tested it with a fresh installation of ember-cli 1.13.13 without any problems. Which version of ember-cli were you using? Apparently 0.2.3 had an issue (https://github.com/ember-cli/ember-cli/pull/3846)
