### ISSUE TITLE
Can't run a production build against 1.0.0-rc.3

### ISSUE THREAD

**Issue by rstudner** [kaliber5/ember-bootstrap#468]
Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: 1.0.0-rc.3 -> 1.0.0-rc.3
ember-cli: ~2.16.2 -> 2.16.2
bootstrap: n/a
bootstrap-sass: ^3.3.7 -> 3.3.7
ember-cli-sass: 7.0.0 -> 7.0.0
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
importBootstrapCSS: false
```
Basically, if I upgrade from 1.0.0-rc.2 to 1.0.0-rc.3 I can't run a production build (locally or on circle ci)

Output/Error:
```
cleaning up...
Build failed.
The Broccoli Plugin: [Fingerprint] failed with:
Error: ENOENT: no such file or directory, open '/Users/roger.studner/git/ember-ui/tmp/uglify_writer-input_base_path-tMpRnfUD.tmp/assets/popper.js.map'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at UglifyWriter.processFile (/Users/roger.studner/git/ember-ui/node_modules/broccoli-uglify-sourcemap/index.js:101:41)
    at /Users/roger.studner/git/ember-ui/node_modules/broccoli-uglify-sourcemap/index.js:65:16
    at Array.forEach (native)
    at /Users/roger.studner/git/ember-ui/node_modules/broccoli-uglify-sourcemap/index.js:55:25
    at Array.forEach (native)
    at UglifyWriter.build (/Users/roger.studner/git/ember-ui/node_modules/broccoli-uglify-sourcemap/index.js:54:19)
    at /Users/roger.studner/git/ember-ui/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/roger.studner/git/ember-ui/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/roger.studner/git/ember-ui/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/roger.studner/git/ember-ui/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/roger.studner/git/ember-ui/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)


The broccoli plugin was instantiated at:
    at Fingerprint.Plugin (/Users/roger.studner/git/ember-ui/node_modules/broccoli-plugin/index.js:7:31)
    at Fingerprint.Filter [as constructor] (/Users/roger.studner/git/ember-ui/node_modules/broccoli-filter/index.js:34:10)
    at new Fingerprint (/Users/roger.studner/git/ember-ui/node_modules/broccoli-asset-rev/lib/fingerprint.js:21:10)
    at Fingerprint (/Users/roger.studner/git/ember-ui/node_modules/broccoli-asset-rev/lib/fingerprint.js:16:12)
    at new AssetRev (/Users/roger.studner/git/ember-ui/node_modules/broccoli-asset-rev/lib/asset-rev.js:31:25)
    at AssetRev (/Users/roger.studner/git/ember-ui/node_modules/broccoli-asset-rev/lib/asset-rev.js:7:12)
    at Class.postprocessTree (/Users/roger.studner/git/ember-ui/node_modules/broccoli-asset-rev/index.js:31:40)
    at projectOrAddon.addons.reduce (/Users/roger.studner/git/ember-ui/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (native)
    at addonProcessTree (/Users/roger.studner/git/ember-ui/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/Users/roger.studner/git/ember-ui/node_modules/ember-cli/lib/broccoli/ember-app.js:661:12)
    at EmberApp.toTree (/Users/roger.studner/git/ember-ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1814:17)
    at module.exports (/Users/roger.studner/git/ember-ui/ember-cli-build.js:49:14)
    at Builder.setupBroccoliBuilder (/Users/roger.studner/git/ember-ui/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/Users/roger.studner/git/ember-ui/node_modules/ember-cli/lib/models/builder.js:30:10)
    at BuildTask.run (/Users/roger.studner/git/ember-ui/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/Users/roger.studner/git/ember-ui/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatch (/Users/roger.studner/git/ember-ui/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/roger.studner/git/ember-ui/node_modules/rsvp/dist/rsvp.js:538:13)
    at /Users/roger.studner/git/ember-ui/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/Users/roger.studner/git/ember-ui/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by simonihmig** [comment]
Seems to be related to https://github.com/kybishop/ember-popper/issues/46

**Comment by simonihmig** [comment]
@rstudner do you have any special settings regarding preserving sourcemaps in production, or just default config?

**Comment by rstudner** [comment]
@simonihmig :) Yes, I do generate sourcemaps (always) for all builds.   It is exactly the issue you linked to.

**Comment by urbany** [comment]
@rstudner I detailed a way to fix this in the meanwhile: https://github.com/kybishop/ember-popper/issues/46#issuecomment-336441648

**Comment by simonihmig** [comment]
This has been fixed in https://github.com/kybishop/ember-popper/pull/48 and released in 0.6.5 of ember-popper. After updating your dependencies (and updating your `yarn.lock` in case this is used) the error should hopefully disappear.

**Comment by andyhot** [comment]
@simonihmig, 1.0.0-rc.2 is the last version where vendor sourcemaps are produced correctly for me. https://github.com/kybishop/ember-popper/pull/48 has fixed the production builds but the produced sourcemaps are broken

**Comment by rstudner** [comment]
"Sourcemaps are broken" appears to be the norm and not the exception (at least in my experience).  Not necessaril related to ember-bootstrap but just ember in general.

Combine that with ember-cli-uglify vs the ember docs prescribing two totally unrelated ways to configure an ember app to produce sourcemaps and the confusing isn't surprising :)

**Comment by andyhot** [comment]
Well, i generally didn't have any problems with sourcemaps and I didn't mean to say it's ember-bootstrap's fault. I just wanted to write it down in case others stumble upon this.

In this particular case, it's https://github.com/kratiahuja/fastboot-transform/issues/6 that needs some love - i already have an ugly PR that works for me and looking to improve and merge

**Comment by rstudner** [comment]
You certainly are luckier than I then :)

I produce sourcemaps, even for production builds, but find they are rarely accurate (anywhere) and of little to no use.  I can't set breakpoints in them or use them for useful purposes (in firefox or chrome).

I can at least point my dev environment at a distant API via --proxy and that works.. but otherwise, nada.
