### ISSUE TITLE
 Cannot read property 'import' of undefined

### ISSUE THREAD

**Issue by Jalil-Irfan** [kaliber5/ember-bootstrap#572]
---
I am creating a new ember app at my home
I added ember-bootstrap add-on since then im unable to run my local
I get the error saying import undefined for ember-popper in ember-bootstrap
```Cannot read property 'import' of undefined
TypeError: Cannot read property 'import' of undefined
    at CoreObject.included (E:\Interview\wekancode\wekancode\node_modules\ember-bootstrap\node_modules\ember-popper\index.js:32:16)
    at CoreObject.superWrapper [as included] (E:\Interview\wekancode\wekancode\node_modules\ember-cli\node_modules\core-object\lib\assign-properties.js:32:18)
    at E:\Interview\wekancode\wekancode\node_modules\ember-cli\lib\models\addon.js:248:34
    at Array.map (native)
    at CoreObject.eachAddonInvoke (E:\Interview\wekancode\wekancode\node_modules\ember-cli\lib\models\addon.js:246:24)
    at CoreObject.extend.included (E:\Interview\wekancode\wekancode\node_modules\ember-cli\lib\models\addon.js:385:10)
    at CoreObject.superWrapper [as included] (E:\Interview\wekancode\wekancode\node_modules\ember-cli\node_modules\core-object\lib\assign-properties.js:32:18)
    at CoreObject.included (E:\Interview\wekancode\wekancode\node_modules\ember-bootstrap\index.js:70:26)
    at CoreObject.superWrapper [as included] (E:\Interview\wekancode\wekancode\node_modules\ember-cli\node_modules\core-object\lib\assign-properties.js:32:18)
    at EmberApp.<anonymous> (E:\Interview\wekancode\wekancode\node_modules\ember-cli\lib\broccoli\ember-app.js:435:15)
```

My ember-cli-build
```
/*jshint node:true*/
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    'ember-bootstrap': {
      'bootstrapVersion': 3,
      'importBootstrapFont': true,
      'importBootstrapCSS': true
    }
  });

  return app.toTree();
};

```

What am i missing please let me know

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Cannot find module 'core-object'
Error: Cannot find module 'core-object'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\Interview\wekancode\wekancode\node_modules\ember-bootstrap\lib\tasks\info.js:3:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by Jalil-Irfan** [comment]
WiIl try and let you know

**Comment by simonihmig** [comment]
Closing this for now, feel free to reopen if you are sure there is a problem in this addon!
