### ISSUE TITLE
plugin incompatible with ember fastboot

### ISSUE THREAD

**Issue by maerten** [kaliber5/ember-bootstrap#75]
Hi, this plugin seems to break ember fastboot due to transitions.js referencing a global jQuery variable (which is available as window.jQuery in ember fastboot). Ember CLI version 2.4.3

**Comment by simonihmig** [comment]
I have not had the chance to try fastboot yet, but I changed transition.js to access jQuery through `window.jQuery` as suggested. This is available in the branch fastboot-patch. 

@maerten Can you please update ember-bootstrap in your app (use `ember-bootstrap: "kaliber5/ember-bootstrap#fastboot-patch"` in your `package.json` followed by `npm install`) and check if the change fixed the issue for you?

**Comment by openhouse** [comment]
I just tested this. And it didn't' work.

I set up the Ember FastBoot Quickstart project. (really quick!)
https://www.ember-fastboot.com/quickstart

FastBoot started and worked correctly.

Installed Ember-Bootstrap.
`ember install ember-bootstrap`

Used the branch you posted.
`"kaliber5/ember-bootstrap#fastboot-patch"`
`npm install`

Started FastBoot
`ember fastboot --serve-assets`

and got this error
```
Cannot read property 'fn' of undefined
/Users/jburkart/Sites/sandbox/github-fastboot-example/dist/fastboot/vendor.js:66748
  $.fn.emulateTransitionEnd = function (duration) {
   ^
TypeError: Cannot read property 'fn' of undefined
    at /Users/jburkart/Sites/sandbox/github-fastboot-example/dist/fastboot/vendor.js:66748:4
    at /Users/jburkart/Sites/sandbox/github-fastboot-example/dist/fastboot/vendor.js:66771:2
    at Sandbox.VMSandbox.eval (/Users/jburkart/Sites/sandbox/github-fastboot-example/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/lib/vm-sandbox.js:14:14)
    at EmberApp.retrieveSandboxedApp (/Users/jburkart/Sites/sandbox/github-fastboot-example/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/lib/ember-app.js:134:13)
    at new EmberApp (/Users/jburkart/Sites/sandbox/github-fastboot-example/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/lib/ember-app.js:47:21)
    at FastBoot._buildEmberApp (/Users/jburkart/Sites/sandbox/github-fastboot-example/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/index.js:102:17)
    at new FastBoot (/Users/jburkart/Sites/sandbox/github-fastboot-example/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/index.js:47:10)
    at fastbootExpressMiddleware (/Users/jburkart/Sites/sandbox/github-fastboot-example/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/index.js:24:16)
    at /Users/jburkart/Sites/sandbox/github-fastboot-example/node_modules/ember-cli-fastboot/lib/commands/fastboot.js:32:26
    at lib$rsvp$$internal$$tryCatch (/Users/jburkart/Sites/sandbox/github-fastboot-example/node_modules/ember-cli-fastboot/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jburkart/Sites/sandbox/github-fastboot-example/node_modules/ember-cli-fastboot/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/jburkart/Sites/sandbox/github-fastboot-example/node_modules/ember-cli-fastboot/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/jburkart/Sites/sandbox/github-fastboot-example/node_modules/ember-cli-fastboot/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Looking at Ember-Paper they added the following guard to their addon's index.js
```
  included: function(app) {
    this._super.included(app);

    if (!process.env.EMBER_CLI_FASTBOOT) {
      app.import(app.bowerDirectory + '/hammer.js/hammer.js')
      app.import(app.bowerDirectory + '/matchMedia/matchMedia.js');
    };

    app.import('vendor/propagating.js');
  },
```
https://github.com/miguelcobain/ember-paper/pull/347/commits/dbb0c34cab2b3c7d595baff8c469207fe261aa08
