### ISSUE TITLE
Problem with build (ember 2.4.1)

### ISSUE THREAD

**Issue by tivak** [kaliber5/ember-bootstrap#81]
I have problem with current project and try to create new to test issue.

> $ ember new ttt
> $ cd ttt
> $ ember install ember-bootstrap
> $ npm install
> $ ember build
version: 2.4.1
Build failed.
The Broccoli Plugin: [BroccoliMergeTrees: Addon#treeFor (ember-bootstrap - addon)] failed with:
Error: ENOENT: no such file or directory, stat 'D:\ttt\tmp\broccoli_merge_trees-input_base_path-BVa0GyhY.tmp\1\modules\ember-wormhole'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at buildEntry (D:\ttt\node_modules\ember-cli\node_modules\broccoli-merge-trees\index.js:264:17)
    at BroccoliMergeTrees._mergeRelativePath (D:\ttt\node_modules\ember-cli\node_modules\broccoli-merge-trees\index.js:185:19)
    at BroccoliMergeTrees._mergeRelativePath (D:\ttt\node_modules\ember-cli\node_modules\broccoli-merge-trees\index.js:238:31)
    at BroccoliMergeTrees.build (D:\ttt\node_modules\ember-cli\node_modules\broccoli-merge-trees\index.js:50:24)
    at D:\ttt\node_modules\ember-cli\node_modules\broccoli-plugin\read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (D:\ttt\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\ttt\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\ttt\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1019:11)

> The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (D:\ttt\node_modules\ember-cli\node_modules\broccoli-plugin\index.js:7:31)
    at new BroccoliMergeTrees (D:\ttt\node_modules\ember-cli\node_modules\broccoli-merge-trees\index.js:29:10)
    at BroccoliMergeTrees (D:\ttt\node_modules\ember-cli\node_modules\broccoli-merge-trees\index.js:23:53)
    at mergeTrees (D:\ttt\node_modules\ember-cli\lib\models\addon.js:35:14)
    at Class.treeFor (D:\ttt\node_modules\ember-cli\lib\models\addon.js:300:10)
    at D:\ttt\node_modules\ember-cli\lib\broccoli\ember-app.js:446:20
    at Array.map (native)
    at EmberApp.addonTreesFor (D:\ttt\node_modules\ember-cli\lib\broccoli\ember-app.js:444:30)
    at EmberApp._addonTree (D:\ttt\node_modules\ember-cli\lib\broccoli\ember-app.js:819:36)
    at EmberApp._processedVendorTree (D:\ttt\node_modules\ember-cli\lib\broccoli\ember-app.js:864:20)

**Comment by tivak** [comment]
I am sorry, it is not problem of ember-bootstrap
