### ISSUE TITLE
ember TypeError: (0 , _component.classNameBindings) is not a function (^3.0.0-rc.5)

### ISSUE THREAD

**Issue by basz** [kaliber5/ember-bootstrap#895]
Output from `ember bootstrap:info`:

```
ember-bootstrap: ^3.0.0-rc.5 -> 3.0.0-rc.5
ember-cli: ~3.11.0 -> 3.11.0
bootstrap: ^4.3.1 -> 4.3.1
bootstrap-sass: n/a
ember-cli-sass: ^9.0.0 -> 9.0.1
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapCSS: false
importBootstrapTheme: false
importBootstrapFont: false
whitelist: undefined
```

application/template.hbs
```
<BsNav @type="pills" as |nav|>
  
</BsNav>
```

edit: ^3.0.0-rc.1 did worked

```
console-consumer.js:12 ember TypeError: (0 , _component.classNameBindings) is not a function
    at Module.callback (https://localhost:4201/assets/vendor.js:163435:173)
    at Module.exports (https://localhost:4201/assets/vendor.js:111:32)
    at Module._reify (https://localhost:4201/assets/vendor.js:148:59)
    at Module.reify (https://localhost:4201/assets/vendor.js:135:27)
    at Module.exports (https://localhost:4201/assets/vendor.js:109:10)
    at Module._reify (https://localhost:4201/assets/vendor.js:148:59)
    at Module.reify (https://localhost:4201/assets/vendor.js:135:27)
    at Module.exports (https://localhost:4201/assets/vendor.js:109:10)
    at requireModule (https://localhost:4201/assets/vendor.js:32:18)
    at Class._extractDefaultExport (https://localhost:4201/assets/vendor.js:206118:20)
    at Class.resolveOther (https://localhost:4201/assets/vendor.js:205795:32)
    at Class.resolve (https://localhost:4201/assets/vendor.js:205855:25)
    at resolve (https://localhost:4201/assets/vendor.js:18260:36)
    at Registry.resolve (https://localhost:4201/assets/vendor.js:17800:21)
    at Registry.resolve (https://localhost:4201/assets/vendor.js:17803:33)
    at factoryFor (https://localhost:4201/assets/vendor.js:17360:38)
    at Container.factoryFor (https://localhost:4201/assets/vendor.js:17275:14)
    at Class.factoryFor (https://localhost:4201/assets/vendor.js:45758:33)
    at Class.componentFor [as _super] (https://localhost:4201/assets/vendor.js:49783:20)
    at Class.componentFor (https://localhost:4201/assets/vendor.js:178858:28)
    at Class.superWrapper [as componentFor] (https://localhost:4201/assets/vendor.js:49075:22)
    at lookupComponentPair (https://localhost:4201/assets/vendor.js:51650:37)
    at lookupComponent (https://localhost:4201/assets/vendor.js:51670:12)
    at RuntimeResolver._lookupComponentDefinition (https://localhost:4201/assets/vendor.js:29419:38)
    at RuntimeResolver.lookupComponentHandle (https://localhost:4201/assets/vendor.js:29193:37)
    at CompileTimeLookup.lookupComponentDefinition (https://localhost:4201/assets/vendor.js:25833:28)
    at LazyCompiler.resolveLayoutForTag (https://localhost:4201/assets/vendor.js:61663:29)
    at https://localhost:4201/assets/vendor.js:60836:28
    at Compilers.compile (https://localhost:4201/assets/vendor.js:60750:7)
    at compile (https://localhost:4201/assets/vendor.js:61443:17)
    at LazyCompiler.add (https://localhost:4201/assets/vendor.js:61637:14)
    at CompilableProgram.compile (https://localhost:4201/assets/vendor.js:61401:44)
    at OutletComponentManager.getLayout (https://localhost:4201/assets/vendor.js:24031:24)
    at Object.evaluate (https://localhost:4201/assets/vendor.js:66405:24)
    at AppendOpcodes.evaluate (https://localhost:4201/assets/vendor.js:64794:19)
    at LowLevelVM.evaluateSyscall (https://localhost:4201/assets/vendor.js:68007:22)
    at LowLevelVM.evaluateInner (https://localhost:4201/assets/vendor.js:67953:14)
    at LowLevelVM.evaluateOuter (https://localhost:4201/assets/vendor.js:67945:14)
    at VM.next (https://localhost:4201/assets/vendor.js:70011:20)
    at TemplateIteratorImpl.next (https://localhost:4201/assets/vendor.js:70047:22)
    at RootState.render (https://localhost:4201/assets/vendor.js:25071:37)
    at TransactionRunner.runInTransaction (https://localhost:4201/assets/vendor.js:31409:35)
    at runInTransaction (https://localhost:4201/assets/vendor.js:31544:74)
    at InteractiveRenderer._renderRoots (https://localhost:4201/assets/vendor.js:25367:78)
    at InteractiveRenderer._renderRootsTransaction (https://localhost:4201/assets/vendor.js:25404:14)
    at InteractiveRenderer._renderRoot (https://localhost:4201/assets/vendor.js:25324:12)
    at InteractiveRenderer._appendDefinition (https://localhost:4201/assets/vendor.js:25240:12)
    at InteractiveRenderer.appendOutletView (https://localhost:4201/assets/vendor.js:25226:12)
    at invokeWithOnError (https://localhost:4201/assets/vendor.js:71332:18)
    at Queue.flush (https://localhost:4201/assets/vendor.js:71212:13)
    at DeferredActionQueues.flush (https://localhost:4201/assets/vendor.js:71409:21)
    at Backburner._end (https://localhost:4201/assets/vendor.js:71943:34)
    at Backburner.end (https://localhost:4201/assets/vendor.js:71693:12)
    at Backburner._run (https://localhost:4201/assets/vendor.js:71998:16)
    at Backburner._join (https://localhost:4201/assets/vendor.js:71972:21)
    at Backburner.join (https://localhost:4201/assets/vendor.js:71743:19)
    at join (https://localhost:4201/assets/vendor.js:59267:23)
    at HTMLDocument.<anonymous> (https://localhost:4201/assets/vendor.js:59362:25)
    at mightThrow (https://localhost:4201/assets/vendor.js:9710:29)
    at process (https://localhost:4201/assets/vendor.js:9778:12)
```

**Comment by jelhan** [comment]
I'm unable to reproduce using a newly created project. Are you able to reproduce in a CodeSandbox or add more detailed steps for reproduction?

**Comment by basz** [comment]
`yarn why ember-decorators` told me I had one version. Updating `ember-best-language` got rid of it. 

Also got rid of some other unused stuff with help of `dependency linting` (thx!).
And I went from ember-cli 3.11 to 3.12...

Now `3.0.0-rc.5` works 🎉 

Interestingly the only 'conflict' shown by dependency listing now comes from ember-bootstrap... 😆 

```
ember-angle-bracket-invocation-polyfill
Allowed: (any single version)
Found: 2.0.2, 1.3.1
lab-plhw
└─┬ ember-bootstrap
  ├── ember-angle-bracket-invocation-polyfill@2.0.2
  └─┬ ember-popper
    └── ember-angle-bracket-invocation-polyfill@1.3.1
```

Thanks!

**Comment by jelhan** [comment]
@basz Seems like you are on an old version of ember-popper subdependency. Try another `yarn upgrade ember-bootstrap` to fix it. Double-check that you haven't pinned that subdependency using yarn resolutions. You should use `ember-popper@0.10.1`, which depends on `ember-angle-bracket-invocation-polyfill@^2.0.2`.

**Comment by basz** [comment]
except only ember bootstrap uses it if i get this right...

```
➜  hf-app-lab git:(upgrade/emberjs) ✗ yarn why ember-popper

yarn why v1.17.3
[1/4] 🤔  Why do we have the module "ember-popper"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "ember-popper@0.10.1"
info Reasons this module exists
   - "_project_#lab-plhw#ember-bootstrap" depends on it
   - Hoisted from "_project_#lab-plhw#ember-bootstrap#ember-popper"
info Disk size without dependencies: "1.39MB"
info Disk size with unique dependencies: "7.47MB"
info Disk size with transitive dependencies: "55.68MB"
info Number of shared dependencies: 133
✨  Done in 1.97s.
```

**Comment by BryanHunt** [comment]
I just hit this error after upgrading EmberJS to 3.13 and ember-bootstrap to 3.0.0-rc6.

```
➜  nv-k8s-ui git:(develop) ✗ yarn why ember-popper
yarn why v1.17.3
[1/4] 🤔  Why do we have the module "ember-popper"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "ember-popper@0.10.2"
info Reasons this module exists
   - "ember-bootstrap" depends on it
   - Hoisted from "ember-bootstrap#ember-popper"
```

**Comment by BryanHunt** [comment]
After some more digging, I found the problem:

```
➜  nv-k8s-ui git:(develop) ✗ yarn why ember-decorators
yarn why v1.17.3
[1/4] 🤔  Why do we have the module "ember-decorators"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "ember-decorators@5.2.0"
info Reasons this module exists
   - "ember-yeti-table" depends on it
   - Hoisted from "ember-yeti-table#ember-decorators"
info Disk size without dependencies: "648KB"
info Disk size with unique dependencies: "2.12MB"
info Disk size with transitive dependencies: "58.2MB"
info Number of shared dependencies: 128
=> Found "ember-bootstrap#ember-decorators@6.1.1"
info This module exists because "ember-bootstrap" depends on it.
info Disk size without dependencies: "80KB"
info Disk size with unique dependencies: "1.04MB"
info Disk size with transitive dependencies: "57.2MB"
info Number of shared dependencies: 125
```

I removed yeti-table and the problem is fixed.
